### ISSUE TITLE
cannot get it to work under mycroft plasma widget

### ISSUE THREAD

**Issue by ianni67** [JarbasSkills/ZZZ-fallback-cleverbot#1]
Hi, I'm pretty new to both mycroft and JarbasAI fork.
I've been pointed here from the mycroft web site, while searching for a chatterbot fallback skill.
I issued the command (actually told to mycroft) "install cleverbot".
I got the answer that the skill was installed, but after that, it does not work (does not know cleverbot).
Where am I wrong?

**Comment by ianni67** [comment]
Oh! if I get it right, cleverbot is a paid service, so probably the problem is that I did not sign-on for the service from cleverbot.com, am I right?

**Comment by JarbasAl** [comment]
you need to get an api key, the skill was updated to use mycroft home backend, you need to add your key to the skill settings at home.mycroft.ai
